version: '3.9'

services:
  db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn -b 0.0.0.0:8000 -w 4 openotes.wsgi:application"
    container_name: OpeNotes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
        - .env  
    depends_on:
      - db

volumes:
  postgres_data: