version: '3.9'

services:
  db:
    image: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  web:
    build: .
    command: "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    container_name: Berg
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
        - .env  
    depends_on:
      - db

volumes:
  postgres_data: