# Generated by Django 4.2.7 on 2023-11-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laporan',
            old_name='status',
            new_name='reviewed',
        ),
    ]
