# Generated by Django 4.2.7 on 2023-11-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_status_laporan_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
