# Generated by Django 4.2.7 on 2023-11-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_laporan_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
