# Generated by Django 4.2.7 on 2023-11-28 20:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
