# Generated by Django 4.2.7 on 2023-11-30 02:59

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_vote_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='description',
            new_name='body',
        ),
        migrations.AddField(
            model_name='notes',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='notes.notes'),
        ),
        migrations.AddField(
            model_name='notes',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
