# Generated by Django 4.2.7 on 2023-11-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_note_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
