# Generated by Django 4.2.7 on 2023-12-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder_favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldernotes',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_notes', to='folder_favorite.folderfavorite'),
        ),
    ]
