# Generated by Django 4.2.7 on 2023-11-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_note_notes'),
        ('folder_favorite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_favorite.folderfavorite')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notes')),
            ],
        ),
    ]
