# Generated by Django 4.2.7 on 2023-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_favorite', '0002_foldernotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderfavorite',
            name='notes_count',
            field=models.IntegerField(default=0),
        ),
    ]
